services:
  bitcoin-monitor:
    build: .
    container_name: bitcoin-price-monitor-auto
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
    networks:
      - bitcoin-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://httpbin.org/get', timeout=5)"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 2m
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "com.bitcoin.monitor=automated"
      - "com.bitcoin.schedule=daily-9am"

networks:
  bitcoin-network:
    driver: bridge

volumes:
  bitcoin-logs:
